name: End-to-end tests
on: [push]
jobs:
  cypress-run-chrome:
    runs-on: ubuntu-16.04
    name: Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm start
          browser: chrome
  cypress-run-firefox:
    runs-on: ubuntu-16.04
    name: Firefox
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm start
          browser: firefox
  coverage:
    needs: [ cypress-run-chrome ]
    name: coverage
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm start coverage-start
          browser: chrome
      - uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: b3baf277acc00570cddb0c6c78a7c539eb9d4391cc7611d1709ae892e7d76425
        with:
          coverageCommand: npm run coverage-report
